### PR TITLE
Update L1 prefiring weights for muons

### PR DESCRIPTION
**Pull request by JanFSchulte**
The L1 muon prefiring weights have to be updated following a fix for an inconsistency in the measurement, which lead to an overestimated prefiring rate to be used in the correction. See https://cernbox.cern.ch/index.php/s/K1dfiFEiApKjkRY for details.

### CODE REVIEW

**Comment by perrotta** [comment]
@mariadalfonso @JanFSchulte @lathomas : I can hardly follow (from vacations...) all the changes had been overlapped on these weights. Could any of you please confirm that it was **decided/approved** somewhere that these ones are the correct ones for the latest version of #33758?

**Comment by lathomas** [comment]
Yes they are. Does it mean we actually need to restart the tests in https://github.com/cms-sw/cmssw/pull/33759 ?

**Comment by mariadalfonso** [comment]
This file has been tested in the two PR above, both 10_6 and 11_2
The test show changes only to the nano part.
We need this for the nanoV9.

@perrotta @jpata @slava77 do we agree  is ready ?

 @mrodozov can you prepare the distribution to dist for both 10_6 and 11_2 ? Thanks

**Comment by perrotta** [comment]
+1
- Successfully tested with #33758

**Comment by mrodozov** [comment]
+externals

**Comment by qliphy** [comment]
+1

**Pull request merged**
