### PR TITLE
Update of UL2016 and 2017 ECAL prefiring maps (for jets and photons)

### PR DESCRIPTION
**Pull request by lathomas**
This PR is a change to the file containing the jets and photon prefiring maps related to ECAL prefiring for UL processing.  

- The UL2017 maps are slightly updated 
- New TH2F are added for UL2016, separately for pre and post VFP periods. 

The maps were derived using unprefirable events, as discussed in this talk which also presents a validation with dilepton events. 
https://lathomas.web.cern.ch/lathomas/TSGStuff/L1Prefiring/ecalprefiring_ul16and17.pdf

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mariadalfonso** [comment]
@lathomas 
how this gets used ? is there a PR in cms-sw missing ?

**Comment by mariadalfonso** [comment]
@mrodozov 
can we get this in the cms-dist for both master and 10_6 ? 
It has been tested in the two PRs above 

@perrotta, @slava77, @jpata  -- do you agree ?

**Comment by slava77** [comment]
> @mrodozov
> can we get this in the cms-dist for both master and 10_6 ?
> It has been tested in the two PRs above
> 
> @perrotta, @slava77, @jpata -- do you agree ?

this updates an existing file.
https://github.com/cms-sw/cmssw/pull/33759#issuecomment-852671836
in 10_6_X is showing differences in miniAOD, which are not allowed. It's unclear if that can be resolved by a change in the configuration or if we need multiple .root files.
For the latter case, this PR can not go to 10_6_X as is.

**Comment by mrodozov** [comment]
didn't read the last comment, no worries i'll delete the tag
edit:
@slava77 can this go in 12_0 as it is ?

**Comment by slava77** [comment]
> didn't read the last comment, no worries i'll delete the tag
> edit:
> @slava77 can this go in 12_0 as it is ?

yes, it is OK for 12_0_X (the changes in cms-sw/cmssw#33758 were signed by reco)

**Comment by JanFSchulte** [comment]
For 10_6_X, we should be able to keep the miniAOD stable by revertig the switch to the UL maps for ECAL and switch off the application of muon weights. Afaik the old ECAL maps are still in the file, so there is no issue to keep using them. 

 I'll update cms-sw/cmssw#33759 accordingly.

**Pull request merged**
