### PR TITLE
Adding UL17 prefiring maps for photons and jet

### PR DESCRIPTION
**Pull request by lathomas**
This PR adds three new histograms to L1PrefiringMaps.root, corresponding respectively to the L1 prefiring maps for photons, jets (parametrized vs pt and eta), and jets (parametrized vs EMpt and eta) in UL17. They are labelled by the suffix "_UL2017BtoF". 

The file is an input to the prefiring weight producer and is related to this PR: https://github.com/cms-sw/cmssw/pull/32542

The maps (and the file) was tested and validated. See this talk:
https://indico.cern.ch/event/985369/#3-ul2017-prefiring-maps-tbc

Thanks, 
Laurent

### CODE REVIEW

**Comment by slava77** [comment]
since changes in bin files do not compress well in git, please squash the commits into one to avoid increasing the size of the repository (history).
Thank you.

**Comment by lathomas** [comment]
@slava77  done

**Comment by mrodozov** [comment]
can we test this with cms-sw/cmssw#32542 ?

**Comment by perrotta** [comment]
please test with  cms-sw/cmssw#32542

**Comment by mrodozov** [comment]
+externals
it's one new file

**Comment by slava77** [comment]
>  it's one new file

apparently it's an update to the existing file, not a new file

**Comment by perrotta** [comment]
+1
- Data updates to be used by the PR with the updated L1 prefiring weight producer (#32542)

**Comment by mrodozov** [comment]
> > it's one new file
> 
> apparently it's an update to the existing file, not a new file

I'll look closer next time

**Pull request merged**
